### ISSUE TITLE
Product/BUILD FLEXIBLE GRAPH APPLICATIONS WITH LINKURIOUS SDK - Rewording

### ISSUE THREAD

**Issue by mlhommet** [Linkurious/website#16]
BUILD FLEXIBLE GRAPH APPLICATIONS WITH LINKURIOUS SDK
Our SDK helps you build entreprise-grade graph applications or add new capabilities to your existing applications faster.
... image...
The Linkurious SDK offers functionalities to build, test and deploy your own web applications for graph visualization. It includes the Linkurious server REST API and its REST client, a powerful graph visualization library, Ogma, and a detailed documentation to assist the development of your project.
->
BUILD GRAPH APPLICATIONS WITH THE LINKURIOUS SDK
Add custom graph capabilities to your application with the Linkurious SDK.
... image...
The Linkurious SDK offers functionalities to build, test and deploy your own web applications for graph visualization. It includes the Linkurious server REST API and its REST client, a powerful graph visualization library, Ogma, and a detailed documentation to assist you during the development of your project.

**Comment by mlhommet** [comment]
Linkurious provides a layer of high level services available via a REST API on top of your favorite graph databases.
->
The Linkurious Server REST API exposes high-level services built on top of your favorite graph databases.

**Comment by mlhommet** [comment]
FULL TEXT SEARCH
Implement powerful search capabilities on graph data such as autocomplete, fuzzy results or multilingual support.
→
FULL TEXT SEARCH
Access powerful search capabilities on graph data such as autocomplete, fuzzy results or multilingual support.

**Comment by mlhommet** [comment]
SECURITY
Manage access rights for users and groups of users on the entity type and property level and integrate authentication (LDAP, Active Directory, OAuth).
→
SECURITY
Manage access rights for users and groups of users at the entity type and property level and connect to 3rd party authentication services (LDAP, Active Directory, OAuth).

**Comment by mlhommet** [comment]
ALERTS AND MONITORING
Automate and schedule the detection of anomalies and suspicious graph patterns for teams of analysts.
→
ALERTS AND MONITORING
Automate and schedule the detection of anomalies and suspicious graph patterns for teams of analysts to investigate.

**Comment by mlhommet** [comment]
Build your custom interactive graph visualization interface with Ogma, the Javascript library for large-scale graph
->
Build your custom interactive graph visualization interface with Ogma, the Javascript library for large-scale graph.

**Comment by sheymann** [comment]
@mlhommet change rejected due to information loss: "Our SDK helps you build entreprise-grade graph applications or add new capabilities to your existing applications faster." -> "Add custom graph capabilities to your application with the Linkurious SDK."

@jvilledieu thoughts?

**Comment by jvilledieu** [comment]
+1 for information loss. I prefer to be explicit about the new app vs add features to existing app at the cost being longer.
